"""
Direct unit tests for SupervisorAgent.route_and_execute().
"""

import pytest
from unittest.mock import patch, MagicMock, AsyncMock
from app.supervisor import SupervisorAgent
from app.llm_client import LLMError


def test_supervisor_unknown_action():
    """Verify that unknown actions return a graceful error status."""
    agent = SupervisorAgent()
    res = agent.route_and_execute("invalid_action_name", {})
    assert res["status"] == "error"
    assert "Unknown action" in res["message"]


@patch("app.agents.ConceptGraphAgent.build_graph")
@patch("app.database.save_concepts")
@patch("app.database.save_concept_edges")
def test_supervisor_concept_spot(mock_save_edges, mock_save_concepts, mock_build):
    """Verify concept_spot action delegates to ConceptGraphAgent."""
    mock_build.return_value = ([{"label": "TestNode"}], [{"source": "A", "target": "B"}])
    
    agent = SupervisorAgent()
    res = agent.route_and_execute("concept_spot", {"doc_id": "doc123", "document_text": "sample text"})
    
    assert res["status"] == "success"
    assert res["nodes"] == [{"label": "TestNode"}]
    assert res["edges"] == [{"source": "A", "target": "B"}]
    mock_build.assert_called_once_with("doc123", "sample text", llm_client=agent.llm_client)
    mock_save_concepts.assert_called_once()
    mock_save_edges.assert_called_once()


@patch("app.agents.VisualSandboxAgent.generate_spec")
@patch("app.database.save_visual_specs")
def test_supervisor_visual_gen(mock_save_specs, mock_generate):
    """Verify visual_gen action delegates to VisualSandboxAgent."""
    mock_generate.return_value = {"type": "plotly", "spec_json": {}}
    
    agent = SupervisorAgent()
    res = agent.route_and_execute("visual_gen", {
        "doc_id": "doc123",
        "concept_id": "c1",
        "concept_label": "Label",
        "concept_explanation": "Expl"
    })
    
    assert res["status"] == "success"
    assert res["spec"] == {"type": "plotly", "spec_json": {}}
    mock_generate.assert_called_once_with("doc123", "c1", "Label", "Expl", llm_client=agent.llm_client)
    mock_save_specs.assert_called_once()


@patch("app.agents.MasteryEvaluatorAgent.evaluate_response")
def test_supervisor_evaluate(mock_evaluate):
    """Verify evaluate action delegates to MasteryEvaluatorAgent."""
    mock_evaluate.return_value = {
        "scores": {"memory": 80, "comprehension": 70, "structure": 60, "application": 50},
        "reasoning": "Good effort",
        "recommendation": "Next steps"
    }
    
    agent = SupervisorAgent()
    res = agent.route_and_execute("evaluate", {
        "concept_label": "Label",
        "concept_explanation": "Expl",
        "question": "Q?",
        "student_answer": "A",
        "current_scores": {"memory": 50, "comprehension": 50, "structure": 50, "application": 50}
    })
    
    assert res["status"] == "success"
    assert res["scores"]["memory"] == 80
    assert res["reasoning"] == "Good effort"
    mock_evaluate.assert_called_once()


@patch("app.agents.MasteryEvaluatorAgent.generate_quiz_question")
def test_supervisor_quiz_gen(mock_gen_quiz):
    """Verify quiz_gen action delegates to MasteryEvaluatorAgent."""
    mock_gen_quiz.return_value = "Question generated by mock"
    
    agent = SupervisorAgent()
    res = agent.route_and_execute("quiz_gen", {
        "concept_label": "Label",
        "concept_explanation": "Expl"
    })
    
    assert res["status"] == "success"
    assert res["question"] == "Question generated by mock"
    mock_gen_quiz.assert_called_once_with("Label", "Expl", llm_client=agent.llm_client)


@patch("app.graph.graph")
def test_supervisor_chat(mock_graph):
    """Verify chat action delegates to the LangGraph chat workflow."""
    mock_graph.invoke.return_value = {
        "messages": [MagicMock(content="Hello user")],
        "route": "general"
    }
    
    agent = SupervisorAgent()
    res = agent.route_and_execute("chat", {
        "messages": ["hi"],
        "current_doc_id": "doc123",
        "config_dict": {}
    })
    
    assert res["status"] == "success"
    assert res["ai_reply"] == "Hello user"
    assert res["route_taken"] == "general"
    mock_graph.invoke.assert_called_once()


@patch("app.agents.ConceptGraphAgent.build_graph")
def test_supervisor_graceful_llm_error(mock_build):
    """Verify Supervisor converts LLMError to a structured error status."""
    mock_build.side_effect = LLMError("rate_limit", "Rate limit exceeded")
    
    agent = SupervisorAgent()
    res = agent.route_and_execute("concept_spot", {"doc_id": "doc123", "document_text": "text"})
    
    assert res["status"] == "error"
    assert res["error_category"] == "rate_limit"
    assert "all providers failed" in res["message"]
